name: Update Commit Count Badge

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-commit-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Count commits this month
        id: commit_count
        run: |
          count=$(git rev-list --count --since="$(date +%Y-%m-01)" HEAD)
          echo "count=$count" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          sed -i "s/Commits%20this%20month-[0-9]\+/Commits%20this%20month-${{ steps.commit_count.outputs.count }}/" README.md

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git diff --cached --quiet || git commit -m "Update commit count badge"
          git push